apiVersion: v1
kind: Pod   #You can show different kind from kubectl api-resources KIND column
metadata:
  name: pitones
spec:
  containers:
  - name: cont1
    image: python:3.6-alpine
    command: ['sh', '-c',  'echo cont1 >> index.html && python -m http.server 8080']
  - name: cont2
    image: python:3.6-alpine
    command: ['sh', '-c',  'echo cont2 >> index.html && python -m http.server 8081']
  - name: cont3
    image: python:3.6-alpine
    command: ['sh', '-c',  'echo cont3 >> index.html && python -m http.server 8082']  
  - name: cont4
    image: python:3.6-alpine
    command: ['sh', '-c',  'echo cont4 >> index.html && python -m http.server 8083']
  