apiVersion: v1
kind: Pod   #You can show different kind from kubectl api-resources KIND column
metadata:
  name: nginx2
spec:
  containers:
  - name: cont1
    image: nginx:alpine
    ports:
    - containerPort: 80