apiVersion: apps/v1 
kind: Deployment
metadata:
  name: svc-app 
  labels:
    appName: front-app
#this section configure the specs to the replicaset
spec: 
  replicas: 3 #Number of replicas that RS should have
  selector:  # Here we configure the owner and match labels to be part of this RS, is like define the owner
    matchLabels: 
      appName: front-app
#since here we configure the pod's specs
  template:
    metadata: 
      labels:
        appName: front-app #might match with replicaset label created above
    spec: #here pod's specs
      containers:
      - name: front1
        image: nginx:latest

---
apiVersion: v1
kind: Service
metadata:
  name: firts-svc
  labels: 
    app: front-app  #
spec:
  type: ClusterIP #added when we were reviewing the different service types
  #type: ClusterIP #added when we were reviewing the different service typestype: ClusterIP #added when we were reviewing the different service types
  #type: ClusterIP #added when we were reviewing the different service typestype: ClusterIP #added when we were reviewing the different service types
  selector:
    appName: front-app
  ports:
    - protocol: TCP
      port:   8080 #the port to the service
      targetPort: 80 # the port set up in my pod
